CREATE TABLE todos(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    completed TINYINT(1),
    task LONGTEXT,
    user_id VARCHAR(191),
    FOREIGN KEY (user_id) REFERENCES users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
) ENGINE=InnoDB;